//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Fidelite_Client = new HashSet<Fidelite_Client>();
        }
    
        public int id { get; set; }
        public string id_genre { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string num_tel { get; set; }
        public string mail { get; set; }
        public string adresse { get; set; }
        public string complement_adresse { get; set; }
        public string cpt { get; set; }
        public Nullable<System.DateTime> date_crea { get; set; }
        public Nullable<System.DateTime> date_modif { get; set; }
        public Nullable<int> carte_fidelite { get; set; }
        public Nullable<int> pt_fidelite { get; set; }
    
        public virtual Genre Genre { get; set; }
        public virtual Commune Commune { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fidelite_Client> Fidelite_Client { get; set; }
    }
}
