//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commandes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commandes()
        {
            this.Livraison_commande = new HashSet<Livraison_commande>();
            this.Produit_Commande = new HashSet<Produit_Commande>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date_commande { get; set; }
        public Nullable<System.DateTime> date_livraison { get; set; }
        public string etat_commande { get; set; }
        public int id_client { get; set; }
        public Nullable<decimal> montant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Livraison_commande> Livraison_commande { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produit_Commande> Produit_Commande { get; set; }
    }
}
