//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilite
    {
        public int id_disponibilite { get; set; }
        public Nullable<System.DateTime> date_disponibilite { get; set; }
    
        public virtual Disponibilite_produit Disponibilite_produit { get; set; }
    }
}
