//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disponibilite()
        {
            this.Disponibilite_produit = new HashSet<Disponibilite_produit>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date_disponibilite_deb { get; set; }
        public Nullable<System.DateTime> date_dispinbilite_fin { get; set; }
        public bool isPermanant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disponibilite_produit> Disponibilite_produit { get; set; }
    }
}
