//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etat_Produit
    {
        public int id { get; set; }
        public int id_etat { get; set; }
        public int id_produit { get; set; }
        public System.DateTime date_crea { get; set; }
        public int created_by { get; set; }
    
        public virtual Etat Etat { get; set; }
        public virtual Produit Produit { get; set; }
    }
}
