//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fidelite
    {
        public int id { get; set; }
        public string nom { get; set; }
        public string evenement { get; set; }
        public Nullable<System.DateTime> date_deb { get; set; }
        public Nullable<System.DateTime> date_fin { get; set; }
        public Nullable<int> limit_client_prevu { get; set; }
        public Nullable<int> limit_client_reel { get; set; }
        public int point_avantage { get; set; }
        public Nullable<int> point_fidelite_bonus { get; set; }
        public Nullable<int> remise_achat_pourcentage { get; set; }
        public Nullable<int> remise_achat_euro { get; set; }
        public Nullable<double> prix_min { get; set; }
        public Nullable<double> prix_max { get; set; }
        public Nullable<int> age_min { get; set; }
        public Nullable<int> age_max { get; set; }
        public int created_by { get; set; }
        public Nullable<int> modif_by { get; set; }
        public System.DateTime date_crea { get; set; }
        public string specification { get; set; }
        public string commentaire { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
