//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fidelite_Client
    {
        public int id { get; set; }
        public int id_client { get; set; }
        public int id_fidelite { get; set; }
        public System.DateTime date_crea { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Fidelite Fidelite { get; set; }
    }
}
