//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionCommandeEntities : DbContext
    {
        public GestionCommandeEntities()
            : base("name=GestionCommandeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresse> Adresse { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Commandes> Commandes { get; set; }
        public virtual DbSet<Commune> Commune { get; set; }
        public virtual DbSet<Disponibilite> Disponibilite { get; set; }
        public virtual DbSet<Disponibilite_produit> Disponibilite_produit { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<Etat> Etat { get; set; }
        public virtual DbSet<Etat_Produit> Etat_Produit { get; set; }
        public virtual DbSet<Fidelite> Fidelite { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Implantation> Implantation { get; set; }
        public virtual DbSet<Livraison> Livraison { get; set; }
        public virtual DbSet<Livraison_commande> Livraison_commande { get; set; }
        public virtual DbSet<Produit> Produit { get; set; }
        public virtual DbSet<Produit_Commande> Produit_Commande { get; set; }
        public virtual DbSet<Profil> Profil { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TokenPasswordUser> TokenPasswordUser { get; set; }
        public virtual DbSet<Type_livraison> Type_livraison { get; set; }
        public virtual DbSet<User_Profil> User_Profil { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
