//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Implantation
    {
        public int id { get; set; }
        public string nom { get; set; }
        public int adresse_id { get; set; }
        public System.DateTime date_crea { get; set; }
        public int created_by { get; set; }
    
        public virtual Adresse Adresse { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
