//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livraison_commande
    {
        public int id { get; set; }
        public int id_livraison { get; set; }
        public int id_commande { get; set; }
        public int id_adresse { get; set; }
    
        public virtual Commandes Commandes { get; set; }
        public virtual Livraison Livraison { get; set; }
    }
}
