//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenPasswordUser
    {
        public int id { get; set; }
        public string token { get; set; }
        public int idUtilisateur { get; set; }
        public System.DateTime validDate { get; set; }
        public string commentaire { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
