//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.Fidelite = new HashSet<Fidelite>();
            this.Fidelite1 = new HashSet<Fidelite>();
            this.TokenPasswordUser = new HashSet<TokenPasswordUser>();
            this.User_Profil = new HashSet<User_Profil>();
        }
    
        public int id { get; set; }
        public string id_genre { get; set; }
        public string identifiant { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> date_naissance { get; set; }
        public string num_tel { get; set; }
        public string mail { get; set; }
        public string adresse { get; set; }
        public string complement_adresse { get; set; }
        public string cpt { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> date_crea { get; set; }
        public Nullable<System.DateTime> date_modif { get; set; }
        public int etat { get; set; }
    
        public virtual Commune Commune { get; set; }
        public virtual Etat Etat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fidelite> Fidelite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fidelite> Fidelite1 { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TokenPasswordUser> TokenPasswordUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Profil> User_Profil { get; set; }
    }
}
